name: PITA-Report
version: 0.01_01
abstract: Create, load, save and manipulate XML PITA reports
author: Adam Kennedy <adam@phase-n.com>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  Carp: 0
  Params::Util: 0.07
  IO::Handle: 0
  IO::File: 0
  IO::Seekable: 0
  File::Flock: 101.060501
  XML::SAX::ParserFactory: 0.13
  XML::Validator::Schema: 1.08
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
